CreateClientConVar("act3_client_debug", 0, true, false, "")

CreateClientConVar("act3_cam_enable", 1, true, false, "")
CreateClientConVar("act3_cam_always", 0, true, false, "")
CreateClientConVar("act3_cam_znear", 2, true, false, "")
CreateClientConVar("act3_cam_shoulder", 1, true, false, "")

CreateClientConVar("act3_cam_drawviewer", 1, true, false, "")
CreateClientConVar("act3_cam_att", "eyes", true, false, "")
CreateClientConVar("act3_cam_up", -2, true, false, "")
CreateClientConVar("act3_cam_forward", -85, true, false, "")
CreateClientConVar("act3_cam_right", 12, true, false, "")

CreateClientConVar("act3_effect_quality", 3, true, false, "")
CreateClientConVar("act3_shelltime", 60, true, false, "")
CreateClientConVar("act3_shell_disable", 0, true, false, "")

CreateClientConVar("act3_fov", 90, true, false, "")
CreateClientConVar("act3_anticlip", 0, true, false, "")
CreateClientConVar("act3_sensitivity", 1, true, false, "")
CreateClientConVar("act3_invertlook", 0, true, false, "")
CreateClientConVar("act3_hipzoom", 1, true, false, "")
CreateClientConVar("act3_objcam", 0, true, false, "")
CreateClientConVar("act3_insightsfov", 0, true, false, "")
CreateClientConVar("act3_forcedcam", 0, true, false, "")
CreateClientConVar("act3_camerasmoothing", 1, true, false, "")
CreateClientConVar("act3_magdropreload", 0, true, false, "")


CreateClientConVar("act3_fovchangespeed", 4, true, false, "")
CreateClientConVar("act3_weaponsightfov", 75, true, false, "")

CreateClientConVar("act3_npc_usetogive", 1, true, false, "")

CreateClientConVar("act3_giveweapon", "", true, false, "")

CreateClientConVar("act3_cam_relativemotion", 1, true, false, "")

CreateClientConVar("act3_hud_enable", 1, true, false, "")
CreateClientConVar("act3_hud_drawhpanel", 1, true, false, "")
CreateClientConVar("act3_hud_reduce", 0, true, false, "")
CreateClientConVar("act3_hud_r", 255, true, false, "")
CreateClientConVar("act3_hud_g", 255, true, false, "")
CreateClientConVar("act3_hud_b", 255, true, false, "")
CreateClientConVar("act3_hud_a", 255, true, false, "")
CreateClientConVar("act3_hud_crosshair_enable", 1, true, false, "")
CreateClientConVar("act3_hud_crosshair_always", 0, true, false, "")
CreateClientConVar("act3_hud_crosshair_sizemin", 2, true, false, "")
CreateClientConVar("act3_hud_crosshair_sizemax", 8, true, false, "")
CreateClientConVar("act3_hud_crosshair_prongsize", 16, true, false, "")
CreateClientConVar("act3_hud_crosshair_image", "act3hud/prong.png", true, false, "")
CreateClientConVar("act3_hud_crosshair_top", 1, true, false, "")
CreateClientConVar("act3_hud_crosshair_left", 1, true, false, "")
CreateClientConVar("act3_hud_crosshair_right", 1, true, false, "")
CreateClientConVar("act3_hud_crosshair_bottom", 1, true, false, "")
CreateClientConVar("act3_hud_crosshair_r", 255, true, false, "")
CreateClientConVar("act3_hud_crosshair_g", 255, true, false, "")
CreateClientConVar("act3_hud_crosshair_b", 255, true, false, "")
CreateClientConVar("act3_hud_crosshair_a", 255, true, false, "")
CreateClientConVar("act3_hud_crosshair_a_r", 175, true, false, "")
CreateClientConVar("act3_hud_crosshair_a_g", 0, true, false, "")
CreateClientConVar("act3_hud_crosshair_a_b", 0, true, false, "")
CreateClientConVar("act3_hud_crosshair_a_a", 255, true, false, "")

CreateClientConVar("act3_hitmarkers", 0, true, false, "")
CreateClientConVar("act3_hitmarker_time", 0.25, true, false, "")
CreateClientConVar("act3_hitmarker_size", 32, true, false, "")
CreateClientConVar("act3_hitmarker_sounds", 0, true, false, "")
CreateClientConVar("act3_hitmarker_norm_r", 200, true, false, "")
CreateClientConVar("act3_hitmarker_norm_g", 200, true, false, "")
CreateClientConVar("act3_hitmarker_norm_b", 200, true, false, "")
CreateClientConVar("act3_hitmarker_norm_a", 255, true, false, "")
CreateClientConVar("act3_hitmarker_crit_r", 150, true, false, "")
CreateClientConVar("act3_hitmarker_crit_g", 0, true, false, "")
CreateClientConVar("act3_hitmarker_crit_b", 0, true, false, "")
CreateClientConVar("act3_hitmarker_crit_a", 255, true, false, "")
CreateClientConVar("act3_hitmarker_defl_r", 255, true, false, "")
CreateClientConVar("act3_hitmarker_defl_g", 255, true, false, "")
CreateClientConVar("act3_hitmarker_defl_b", 255, true, false, "")
CreateClientConVar("act3_hitmarker_defl_a", 255, true, false, "")

CreateClientConVar("act3_showhints", 1, true, false, "")